
import __ASTRO_IMAGE_IMPORT_ZRw6s0 from "./images/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md";
import __ASTRO_IMAGE_IMPORT_Z1oqjJX from "./images/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md";
import __ASTRO_IMAGE_IMPORT_Z1Ukx2V from "./images/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md";
import __ASTRO_IMAGE_IMPORT_Z2reKkT from "./images/4.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md";
import __ASTRO_IMAGE_IMPORT_iTgs5 from "./images/shoe-04.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md";
import __ASTRO_IMAGE_IMPORT_ZcYVOS from "./images/shoe-05.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md";
import __ASTRO_IMAGE_IMPORT_ZITa7Q from "./images/shoe-06.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md";
export default new Map([["./images/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md", __ASTRO_IMAGE_IMPORT_ZRw6s0], ["./images/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md", __ASTRO_IMAGE_IMPORT_Z1oqjJX], ["./images/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md", __ASTRO_IMAGE_IMPORT_Z1Ukx2V], ["./images/4.png?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md", __ASTRO_IMAGE_IMPORT_Z2reKkT], ["./images/shoe-04.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md", __ASTRO_IMAGE_IMPORT_iTgs5], ["./images/shoe-05.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md", __ASTRO_IMAGE_IMPORT_ZcYVOS], ["./images/shoe-06.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Froundups%2F30-early-20s-shoe-fashion.md", __ASTRO_IMAGE_IMPORT_ZITa7Q]]);
		